name: Docker Image

on:
  schedule:
    - cron: "0 14 * * *" # everyday at 2pm
  push:
    branches: ["**"]
    tags: ["v*.*.*"]

env:
  platforms: linux/amd64

jobs:
  main:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set imageName based on the repository name
        id: step_one
        run: |
            imageName="${GITHUB_REPOSITORY/docker-/}"
            echo $imageName
            echo "imageName=$imageName" >> $GITHUB_ENV
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.imageName }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ env.platforms }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.imageName }}:${{ steps.docker_meta.outputs.version }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"
